### ISSUE TITLE
Fix failing test cases, improve coverage

### ISSUE THREAD

**Issue by ThennarasuTW** [Anandsg/Hungry-hero#108]
The `Header.test.js` is failing. 
I'm planning to fix the failing tests and add the below test cases

- Click login button and expect the `useGoogleLogin` function to be called
- Click logout button and expect the `localStorage.removeItem("accessToken")` to be called

Please assign this issue to me if its valid.

**Comment by Anandsg** [comment]
Go ahead

**Comment by ThennarasuTW** [comment]
Thanks, please let me know if you have any file that needs test cases on priority. I will work on them after this.

**Comment by Anandsg** [comment]
You can go ahead and test the functionality mentioned above since it's a small-sized app. I'd like to provide opportunities to other developers as well. If you come across any issues during your analysis, please create them. This would be helpful for me to assign tasks to other developers. Thank you for your contribution.
