### ISSUE TITLE
Enhancement of Dark Mode

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Anandsg/Hungry-hero#133]
I will improve the dark mode button. In dark mode, the buttons '+' or '-' are not clear. If there any other issues in dark mode I will address them and fix it.

In the screenshot below, you can see that the dark mode button is not centered, and the buttons are not visible in dark mode.
![Screenshot 2023-10-09 195641](https://github.com/Anandsg/Hungry-hero/assets/102857774/ff55a9d3-f063-4a08-9db9-e1f610caff4c)
![Screenshot 2023-10-09 195658](https://github.com/Anandsg/Hungry-hero/assets/102857774/b94edc43-2bc3-4610-8cdc-e694fadf8e7e)

Please assign me this issue, and I will fix it.

**Comment by Pinaka-Pani-18** [comment]
While adding and removing from the favorite list, the message is also not visible in dark mode. 
![Screenshot 2023-10-09 200717](https://github.com/Anandsg/Hungry-hero/assets/102857774/8b416f9f-9e94-4423-a96e-8c52b27938e1)

I will identify and fix all the dark mode issues.

**Comment by Anandsg** [comment]
@Pinaka-Pani-18 The dark mode feature got rolled back because it needs to be applied consistently throughout the entire web app. It's a tough nut to crack – you can even see that the empty cart image doesn't look great in dark mode. The cart page, fonts, about page, and especially item cards all need to be styled in dark mode, which is why I pulled the plug on it for now. Feel free to pick any other issue or feature you'd like to tackle!

**Comment by Anandsg** [comment]
@Pinaka-Pani-18 will you able to develop a good dark mode ? if so i will re create a feature issue for it

**Comment by Anandsg** [comment]
sure creating the issue
